server:
  port: 8081
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: SpringTest
  datasource:
    # driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_info?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: KirTheCat228
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  token:
    signing:
      key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG